Try re-instituting the S40network immediate reach IP
git-svn-id: https://svn.code.sf.net/p/freeghost/code/trunk@4960 71f96598-fa45-0410-b640-bcd6f8691b32

diff --git a/src/buildroot/system/skeleton/etc/init.d/S40network b/src/buildroot/system/skeleton/etc/init.d/S40network
--- a/src/buildroot/system/skeleton/etc/init.d/S40network
+++ b/src/buildroot/system/skeleton/etc/init.d/S40network
@@ -9,28 +9,54 @@ if [[ -n $has_usb_nic ]]; then
     echo "Sleeping for 5 seconds to allow USB to sync back with system"
     sleep 5
 fi
-# Enable all interfaces
+# Enable loopback interface
 echo "auto lo" > /etc/network/interfaces
 echo "iface lo inet loopback" >> /etc/network/interfaces
-ifaces=$(ls -1 /sys/class/net | tr -d '@')
-timeout=10
-for iface in $ifaces; do
-    # Check if each interface is up and if not wait up to 10 seconds
-    if [[ x$iface == xlo ]]; then
-        /sbin/ip addr add 127.0.0.1 dev lo
-        /sbin/ip link set lo up
-        continue
-    fi
-    echo "Starting $iface interface"
-    /sbin/ip link set $iface up
-    for delay in $(seq 10); do
-        linkstate=$(/bin/cat /sys/class/net/$iface/carrier)
+echo "" >> /etc/network/interfaces
+/sbin/ip addr add 127.0.0.1 dev lo
+/sbin/ip link set lo up
+primary_ifaces=$(egrep -i "($mac)" /sys/class/net/*/address | awk -F'(/)' '{print $5}')
+for primary_iface in $primary_ifaces; do
+    # Check if each interface is up and if not wait up to 3 seconds
+    echo "Starting $primary_iface interface"
+    echo "auto $primary_iface" >> /etc/network/interfaces
+    echo "iface $primary_iface inet dhcp" >> /etc/network/
+    echo "" >> /etc/network/interfaces
+    /sbin/ip link set $primary_iface up
+    sleep 1
+    for retry in $(seq 3); do
+        linkstate=$(/bin/cat /sys/class/net/$primary_iface/carrier)
         if [[ x$linkstate == x1 ]]; then
-            /sbin/udhcpc -i $iface -t 2 -T $timeout --now
-            [[ $? -eq 0 ]] && break 2
-            let timeout+=5
+            /sbin/udhcpc -i $primary_iface --now
+            [[ $? -eq 0 ]] && exit 0;
+            echo "Trying again on interface $primary_iface..."
         fi
         sleep 1
     done
 done
-exit $?
+ifaces=$(egrep -v -i "($mac|00:00:00:00:00:00)" /sys/class/net/*/address | awk -F'(/)' '{print $5}')
+for iface in $ifaces; do
+    # Check if each interface is up and if not wait up to 10 seconds
+    echo "Starting $iface interface"
+    echo "auto $iface" >> /etc/network/interfaces
+    echo "iface $iface inet dhcp" >> /etc/network/
+    echo "" >> /etc/network/interfaces
+    /sbin/ip link set $iface up
+    sleep 1
+    for retry in $(seq 3); do
+        linkstate=$(/bin/cat /sys/class/net/$iface/carrier)
+        if [[ x$linkstate == x1 ]]; then
+            /sbin/udhcpc -i $iface --now
+            [[ $? -eq 0 ]] && exit 0
+            echo "trying again on interface $iface..."
+        fi
+        sleep 1
+    done
+done
+[[ -z $primary_ifaces && -z $ifaces ]] && echo "No network interfaces found, kernel is probably missing a driver" || "Failed to get an IP!, Tried on interfaces(s): $primary_ifaces $ifaces"
+echo "Please check your network setup and try again!"
+[[ -z $isdebug ]] && sleep 60
+[[ -z $isdebug ]] && reboot
+echo "Press enter to continue"
+read
+exit 1
